In [3]:
import numpy as np
import time

In [2]:
arr = np.array({1, 2, 3, 4, 5})
print(arr, type(arr))

{1, 2, 3, 4, 5} <class 'numpy.ndarray'>


In [6]:
# exexution performance
size = 10_000_000

# python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} seconds")

# numpy arrays
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr ** 2
end = time.time()
print(f"numpy array time = {end-start} seconds")


python list time = 1.65559720993042 seconds
numpy array time = 0.03691554069519043 seconds


In [8]:
# memory
import sys

print(f" python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")

print(f" numpy array size = {np_arr.nbytes} bytes")


 python list size = 800000560000000 bytes
 numpy array size = 80000000 bytes


In [5]:
#create - from lists
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.shape)

arr2D = np.array([[1,2,3], [2,3,4], [5,6,7]])
print(arr2D, arr2D.shape)


arr2 = np.array([1,2,3,4,5,"price"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
[[1 2 3]
 [2 3 4]
 [5 6 7]] (3, 3)
['1' '2' '3' '4' '5' 'price'] <class 'numpy.ndarray'> <U21 (6,)


In [13]:
#create Functions
arr1 = np.zeros((2,3), dtype="int64")  #prefill
print(arr1, arr1.shape)

arr2 = np.ones((2,3), dtype="int64")  #prefill
print(arr2, arr2.shape)

arr3 = np.full((3,4), 100)  # prefill with value
print(arr3, arr3.shape)

arr4 = np.eye(3) # identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(1,10) # range elements
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 4) # evenly spaced arrays
print(arr6, arr6.shape)


[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 2 3 4 5 6 7 8 9] (9,)
[  1.  34.  67. 100.] (4,)


In [20]:
# Properties
arr = np.array([1,2,3,4,5]) #dimensions = n * n
arr1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr1.shape)
print(arr.shape)
print(arr1.size) #total size
print(arr1.dtype)
print(arr1.ndim)

float_arr = arr.astype(np.float64) #Type casting
print(float_arr, float_arr.dtype)

(3, 3)
(5,)
9
int64
2
[1. 2. 3. 4. 5.] float64


In [22]:
# Opeartions on arrays

arr = np.array([[1,2,3], [2,3,4]]) # reshaping is done when we have compatible numbersw eg. (3*5), (5*3)
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

flattened = arr.flatten() # 2D => 1D
print(flattened, flattened.shape)

[[1 2 3]
 [2 3 4]] (2, 3)
[[1 2]
 [3 2]
 [3 4]] (3, 2)
[1 2 3 2 3 4] (6,)


In [32]:
# Indexing
# arr = np.array([1,2,3,4,5])
arr = np.array([[1,2,3], [2,5,4]])
print(arr[1][1])

# Fancy indexing
arr = np.array([1,2,3,4,5])
idx = [0,1,3]
print(arr[idx])

# Boolean indexing
arr = np.array([1,2,3,4,5])
print(arr[arr > 2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])



5
[1 2 4]
[3 4 5]
[2 4]
[1 3 5]


In [34]:
# Slicing
arr = np.array([1,2,3,4,5])
print(arr[1:4]) #[start, end, step]
print(arr[1:])
print(arr[:4])
print(arr[:])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]


In [39]:
# Copy vs view
arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3].copy()
print(sub_arr)

sub_arr[0] = 200
print(sub_arr)
print(arr)


[2 3]
[200   3]
[1 2 3 4 5]


In [44]:
# Multi - dimensional arrays
arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2D)
print(np.sum(arr2D))

# to calculate sum of columns
sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

# to calculate sum of rows
sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [59]:
# 3D arrays
arr3D = np.array([[[1,2], [3,4], [5,6]], [[7,8], [9,10], [11,12]]]) # 2*3*2
print(arr3D, arr3D.shape)

#indexing
print(arr[0,1,1])
print(arr[1,1,0])

#slicing

arr3D[:, 0, :] = 99 # first row from both layers
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
9
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [60]:
# Vectorization
arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(arr + arr2)
print(arr2 + 10)
print(arr ** 2)

[ 7  9 11 13 15]
[16 17 18 19 20]
[ 1  4  9 16 25]


In [61]:
#Broadcasting (scaling)
arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5], [1,2,3,4,5]])
print(arr.shape)
print(arr2.shape)
print(arr + arr2)


(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [68]:
# normalize
arr = np.array([[1,2], [3,4]])
mean = np.mean(arr)
std_dev = np.std(arr)
normalized_arr = (arr - mean) / std_dev
print(mean)
print(std_dev)
print(normalized_arr)
print(np.sqrt(5/4))

2.5
1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
1.118033988749895


In [72]:
# Mathematical fnx
# aggregation

arr = np.array([1,2,3,4,5])
print(arr)
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmax(arr))
print(np.argmin(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

[1 2 3 4 5]
15
120
1
5
4
0
3.0
1.4142135623730951
3.0
2.0


In [74]:
# power fnx
arr = np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 3))

# log
print(np.log(arr))
print(np.log10(arr))

# rounding
print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))


[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
3.0
4.0
3.0
3.0
